# Local environment overrides
controller:
  image:
    repository: ghcr.io/codefin/supergraph-operator
    tag: "latest"
    pullPolicy: IfNotPresent

config:
  routerDeployment: "graph-router"
  supergraphConfigMap: "graph-supergraph"

namespace: vahalla-local
