//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphSchema) DeepCopyInto(out *SubgraphSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphSchema.
func (in *SubgraphSchema) DeepCopy() *SubgraphSchema {
	if in == nil {
		return nil
	}
	out := new(SubgraphSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubgraphSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphSchemaList) DeepCopyInto(out *SubgraphSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubgraphSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphSchemaList.
func (in *SubgraphSchemaList) DeepCopy() *SubgraphSchemaList {
	if in == nil {
		return nil
	}
	out := new(SubgraphSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubgraphSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphSchemaSpec) DeepCopyInto(out *SubgraphSchemaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphSchemaSpec.
func (in *SubgraphSchemaSpec) DeepCopy() *SubgraphSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(SubgraphSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphSchemaStatus) DeepCopyInto(out *SubgraphSchemaStatus) {
	*out = *in
	if in.LastComposed != nil {
		in, out := &in.LastComposed, &out.LastComposed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphSchemaStatus.
func (in *SubgraphSchemaStatus) DeepCopy() *SubgraphSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(SubgraphSchemaStatus)
	in.DeepCopyInto(out)
	return out
}
