apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graph-controller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "graph-controller.controller.labels" . | nindent 4 }}
