{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supergraph-operator.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "supergraph-operator.controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: supergraph-operator
    app.kubernetes.io/component: controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "supergraph-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "supergraph-operator.controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supergraph-operator
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      path: /metrics
{{- end }}
